let teams=[],results=[],rules={},settings={};
const $=s=>document.querySelector(s);function slug(s){return String(s).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')}
async function fetchJSON(p){const r=await fetch('../data/'+p,{cache:'no-store'});return r.json()}
function saveLocal(){localStorage.setItem('mdg_admin',JSON.stringify({teams,results,rules,settings}))}
function loadLocal(){try{const x=JSON.parse(localStorage.getItem('mdg_admin')||'{}');teams=x.teams||teams;results=x.results||results;rules=x.rules||rules;settings=x.settings||settings}catch(e){}}
async function loadAll(){try{teams=await fetchJSON('teams.json');results=await fetchJSON('results.json');rules=await fetchJSON('rules.json');settings=await fetchJSON('settings.json');saveLocal();render();$('#status').innerHTML='<span class="success">Loaded current website data.</span>'}catch(e){$('#status').textContent='Could not load data. Open this through the live website, not directly from your computer.'}}
function clearAdmin(){localStorage.removeItem('mdg_admin');location.reload()}
function render(){loadLocal();$('#runTeam').innerHTML=teams.map(t=>`<option value="${t.id}">${t.name}</option>`).join('');$('#teamList').innerHTML='<h3>Current teams</h3>'+teams.map((t,i)=>`<p><b>${t.name}</b> — ${t.captain||'-'} <button onclick="removeTeam(${i})">Remove</button></p>`).join('');$('#resultList').innerHTML='<h3>Current weeks</h3>'+results.map((w,i)=>`<p><b>Week ${w.week}</b> — ${w.dungeon} — ${w.runs.length} runs <button onclick="removeWeek(${i})">Remove week</button></p>`).join('');$('#rulesRaw').value=JSON.stringify(rules,null,2);$('#settingsRaw').value=JSON.stringify(settings,null,2)}
function addTeam(){const name=$('#teamName').value.trim();if(!name)return alert('Team name is required');const t={id:slug(name),name,captain:$('#captain').value.trim(),realm:$('#realm').value.trim(),faction:$('#faction').value,logo:'',members:$('#members').value.split(',').map(x=>x.trim()).filter(Boolean)};teams.push(t);saveLocal();render()}
function removeTeam(i){teams.splice(i,1);saveLocal();render()}
function addRun(){const week=Number($('#week').value);let w=results.find(x=>Number(x.week)===week);if(!w){w={week,dungeon:$('#dungeon').value.trim(),affix:$('#affix').value.trim(),date:$('#date').value,runs:[]};results.push(w)}w.dungeon=$('#dungeon').value.trim()||w.dungeon;w.affix=$('#affix').value.trim()||w.affix;w.date=$('#date').value||w.date;w.runs.push({teamId:$('#runTeam').value,keyLevel:Number($('#keyLevel').value),time:$('#time').value.trim(),points:Number($('#points').value),proof:$('#proof').value.trim()||'#'});results.sort((a,b)=>a.week-b.week);saveLocal();render()}
function removeWeek(i){results.splice(i,1);saveLocal();render()}
function download(name,obj){const blob=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
function downloadTeams(){download('teams.json',teams)}function downloadResults(){download('results.json',results)}function downloadRules(){try{download('rules.json',JSON.parse($('#rulesRaw').value))}catch(e){alert('Rules JSON has an error')}}function downloadSettings(){try{download('settings.json',JSON.parse($('#settingsRaw').value))}catch(e){alert('Settings JSON has an error')}}
render();loadAll();
